# Generated by Django 5.2.5 on 2025-08-24 19:01

import django.db.models.deletion
import tictactoe.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(default=tictactoe.models.generate_numeric_code, editable=False, max_length=6, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x_player', models.CharField(blank=True, max_length=50, null=True)),
                ('o_player', models.CharField(blank=True, max_length=50, null=True)),
                ('board', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('finished', models.BooleanField(default=False)),
                ('winner', models.CharField(blank=True, max_length=1, null=True)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='games', to='tictactoe.room')),
            ],
        ),
    ]
