# Generated by Django 5.2.5 on 2025-08-24 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tictactoe', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='players',
            field=models.JSONField(default=list),
        ),
    ]
