# Generated by Django 5.2.5 on 2025-09-01 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tictactoe', '0002_room_players'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='host_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
