# Generated by Django 5.2.5 on 2025-09-03 20:11

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tictactoe', '0003_room_host_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='last_activity',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
